[package]
name = "cliente"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.4.1"
gtk = "0.18.1"
gio = "0.19.2"
async-std = "1.10.0"
log = "0.4.14"
fern = "0.6.2"
serde_json = "1.0.114"